lang_code: "ca"

infinitives_jsonl: "data/infinitive-dumps/ca-en-infinitives.jsonl.zst"

meta-data:
  auxiliary: "haver"

  endings:
    - "re"
    - "ar"
    - "er"
    - "ir"

  reflexive-suffixes: [ "-se", "'s" ]


person-data:
  person_map:
    1:
      - ["first-person", "singular"]
    2:
      - ["second-person", "singular"]
      - ["second-person"]  # fallback mapping for imperative
    3:
      - ["third-person", "singular"]
      - ["singular", "formal", "second-person-semantically"]  # fallback mapping for imperative
    4:
      - ["first-person", "plural"]
    5:
      - ["second-person", "plural"]
    6:
      - ["third-person", "plural"]
      - ["plural", "formal", "second-person-semantically"]  # fallback mapping for imperative

  pronouns:
    1: "jo "
    2: "tu "
    3: "ell //ella //vostè "
    4: "nosaltres "
    5: "vosaltres "
    6: "ells //elles //vostès "

  imperative-pronouns:
    1: ""
    2: "(tu) "
    3: "(vostè) "
    4: "(nosaltres) "
    5: "(vosaltres) "
    6: "(vostès) "

  reflexive-pronouns:
    - [ "em ", "m'" ]
    - [ "et ", "t'" ]
    - [ "es ", "s'" ]
    - [ "ens " ]
    - [ "us " ]
    - [ "se ", "s'" ]

category_source:
  path: ["senses", "*", "categories"]
  item: {key: "name"}  # items are dicts, take c["name"]

forms:
    "Infinitiu":
      mode: "infinitivo"
      type: "base_form"
      path:
        - "forms"
      tags: ["infinitive"]

    "Gerundi":
      mode: "gerundio"
      type: "base_form"
      path:
        - "forms"
      tags: ["gerund"]
      on_collision: shortest_length

    "Participi":
      mode: "participio"
      type: "base_form"
      path:
        - "forms"
      tags: ["participle", "masculine", "past", "singular"]
      on_collision: shortest_length

    "Indicatiu Present":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "present"]

    "Indicatiu Imperfet":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "imperfect"]

    "Indicatiu Futur":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "future"]

    "Indicatiu Pretèrit Perfet Simple":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "preterite"]

    "Condicional":
      mode: "condicional"
      path:
        - "forms"
      tags: ["indicative", "conditional"]

    "Subjuntiu Present":
      mode: "subjuntiu"
      path:
        - "forms"
      tags: ["subjunctive", "present"]

    "Subjuntiu Imperfet":
      mode: "subjuntiu"
      path:
        - "forms"
      tags: ["subjunctive", "imperfect"]

    "Imperatiu Afirmatiu":
      mode: "imperatiu"
      path:
        - "forms"
      tags: ["imperative"]
      pronouns: "imperative"

    "Imperatiu Negatiu":
      mode: "imperatiu"
      path:
        - "forms"
      tags: ["imperative", "negative"]
      pronouns: "imperative"
      negation: "no "
