lang_code: "es"

infinitives_jsonl: "data/infinitive-dumps/es-old-infinitives.jsonl.zst"
output_dir: "spanish-test"

meta-data:
  auxiliary: "haber"

  endings:
    - "ar"
    - "er"
    - "ir"

  reflexive-suffixes: [ "se" ]


person-data:
  person_map:
    # first match wins.
    1: ["first-person", "singular"]
    2: ["second-person", "singular"]
    3: ["third-person", "singular"]
    4: ["first-person", "plural"]
    5: ["second-person", "plural"]
    6: ["third-person", "plural"]
    7: ["second-person", "singular", "vos-form"]

  pronouns:
    1: "yo "
    2: "tú "
    3: "él //ella //usted "
    4: "nosotros //nosotras "
    5: "vosotros //vosotras "
    6: "ellos //ellas //ustedes "
    7: "vos "

  reflexive-pronouns: ["me ", "te ", "se ", "nos ", "os "]


category_data:
  transitivity:
    "ES:Verbos intransitivos": "intransitivo"
    "ES:Verbos transitivos": "transitivo"

  verb-group:
    "ES:Verbos de la primera conjugación": "primera conjugación"
    "ES:Verbos de la segunda conjugación": "segunda conjugación"
    "ES:Verbos de la tercera conjugación": "tercera conjugación"

  regularity:
    "ES:Verbos irregulares": "irregular"
    "ES:Verbos regulares": "regular"

complex_category_data:
  paradigma:
    startswith: "ES:Verbos del paradigma "


forms:
    "Infinitivo":
      mode: "infinitivo"
      type: "base_form"
      path:
        - "word"

    "Gerundio":
      mode: "gerundio"
      type: "base_form"
      path:
        - "forms"
      tags: ["impersonal", "gerund"]
      on_collision: shortest_length

    "Participio":
      mode: "participio"
      type: "base_form"
      path:
        - "forms"
      tags: ["impersonal", "participle"]
      on_collision: shortest_length

    "Indicativo Presente":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "present"]

    "Indicativo Imperfecto":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "past", "imperfect"]

    "Indicativo Pretérito Indefinido":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "present", "perfect"]

    "Indicativo Futuro":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "future"]

    "Indicativo Pretérito Perfecto":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "present", "perfect", "compound"]

    "Indicativo Pretérito Pluscuamperfecto":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "pluperfect"]

    "Indicativo Pretérito Anterior":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "past", "anterior", "archaic"]

    "Indicativo Futuro Perfecto":
      mode: "indicativo"
      path:
        - "forms"
      tags: ["indicative", "future", "compound"]

    "Subjuntivo Presente":
      mode: "subjuntivo"
      path:
        - "forms"
      tags: ["subjunctive", "present"]

    "Subjuntivo Pretérito Imperfecto":
      mode: "subjuntivo"
      path:
        - "forms"
      tags: ["subjunctive", "past", "imperfect"]

    "Subjuntivo Futuro":
      mode: "subjuntivo"
      path:
        - "forms"
      tags: ["subjunctive", "future", "archaic"]

    "Subjuntivo Pretérito Perfecto":
      mode: "subjuntivo"
      path:
        - "forms"
      tags: ["subjunctive", "present", "perfect"]

    "Subjuntivo Pretérito Pluscuamperfecto":
      mode: "subjuntivo"
      path:
        - "forms"
      tags: ["subjunctive", "pluperfect"]

    "Subjuntivo Futuro Perfecto":
      mode: "subjuntivo"
      path:
        - "forms"
      tags: ["subjunctive", "archaic", "future", "compound"]

    "Condicional":
      mode: "condicional"
      path:
        - "forms"
      tags: ["conditional"]

    "Condicional Perfecto":
      mode: "condicional"
      path:
        - "forms"
      tags: ["conditional", "compound"]

    "Imperativo Afirmativo":
      mode: "imperativo"
      path:
        - "forms"
      tags: ["imperative", "present"]
