lang_code: "fr"

infinitives_jsonl: "data/infinitive-dumps/fr-fr-infinitives.jsonl.zst"

meta-data:
  auxiliary: french

  endings:
    - "er"
    - "oir"
    - "ir"
    - "re"

  #reflexive-suffixes: [ "-se", "'s" ]
  reflexive-prefixes: [ "se ", "s'" ]

person-data:

  pronouns:
    1: "je "
    2: "tu "
    3: "il //elle //on "
    4: "nous "
    5: "vous "
    6: "ils //elles "

  imperative-pronouns:
    1: ""
    2: "(tu) "
    3: ""
    4: "(nous) "
    5: "(vous) "
    6: ""

  reflexive-pronouns:
    - [ "me ", "m'" ]
    - [ "te ", "t'" ]
    - [ "se ", "s'" ]
    - [ "nous " ]
    - [ "vous " ]
    - [ "se ", "s'" ]

category_source:
  path: ["senses", "*", "categories"]
  item: {key: "name"}  # items are dicts, take c["name"]

forms:
    "Infinitive Présent":
      mode: "infinitif"
      type: "base_form"
      path:
        - "forms"
      tags: ["infinitive", "present"]

    "Infinitive Passé":
      mode: "infinitif"
      type: "base_form"
      path:
        - "forms"
      tags: ["infinitive", "past"]

    "Gérondif Présent":
      mode: "gérondif"
      type: "base_form"
      path:
        - "forms"
      tags: ["gerund", "present"]

    "Gérondif Passé":
      mode: "gérondif"
      type: "base_form"
      path:
        - "forms"
      tags: ["gerund", "past"]

    "Participe Présent":
      mode: "participe"
      type: "base_form"
      path:
        - "forms"
      tags: ["participle", "present"]

    "Participe Passé":
      mode: "participe"
      type: "base_form"
      path:
        - "forms"
      tags: ["participle", "past"]

    "Indicatif Présent":
      mode: "indicatif"
      path:
        - "forms"
      tags: ["indicative", "present"]

    "Indicatif Passé Composé":
      mode: "indicatif"
      path:
        - "forms"
      tags: ["indicative", "past", "multiword-construction"]

    "Indicatif Imparfait":
      mode: "indicatif"
      path:
        - "forms"
      tags: ["indicative", "imperfect"]

    "Indicatif Plusqueparfait":
      mode: "indicatif"
      path:
        - "forms"
      tags: ["indicative", "pluperfect"]

    "Indicatif Passé Simple":
      mode: "indicatif"
      path:
        - "forms"
      tags: ["indicative", "past"]

    "Indicatif Passé Antérieur":
      mode: "indicatif"
      path:
        - "forms"
      tags: ["indicative", "past", "anterior"]

    "Indicatif Futur Simple":
      mode: "indicatif"
      path:
        - "forms"
      tags: ["indicative", "future"]

    "Indicatif Futur Antérieur":
      mode: "indicatif"
      path:
        - "forms"
      tags: ["indicative", "future", "perfect"]

    "Subjonctif Présent":
      mode: "subjonctif"
      path:
        - "forms"
      tags: ["subjunctive", "present"]

    "Subjonctif Passé":
      mode: "subjonctif"
      path:
        - "forms"
      tags: ["subjunctive", "past"]

    "Subjonctif Imparfait":
      mode: "subjonctif"
      path:
        - "forms"
      tags: ["subjunctive", "imperfect"]

    "Subjonctif Plusqueparfait":
      mode: "subjonctif"
      path:
        - "forms"
      tags: ["subjunctive", "pluperfect"]

    "Conditionnel":
      mode: "conditionnel"
      path:
        - "forms"
      tags: ["conditional", "present"]

    "Conditionnel Passé":
      mode: "conditionnel"
      path:
        - "forms"
      tags: ["conditional", "past"]
